### ISSUE TITLE
Display Cluster info in Razeedash while the cluster is being created

### ISSUE THREAD

**Issue by johnymathew** [razee-io/Razee#105]
**Is your feature request related to a problem? Please describe.**
Currently there is no information available about a cluster while it is being created. Usually it takes 30+ minutes to create a cluster and It would be good to display some status of the cluster during that time

**Describe the solution you'd like**
Add a _registerCluster_  API:
`registerCluster (org_id: String!, cluster_name: String!, cluster_id: String!, metadata: JSON): URL!`
Check the cluster_id against the DB and if a cluster exists with this cluster_id then return an error.
if the cluster_id is not in DB add an entry with the status "register" and return a registrationUrl including the cluster_id

**Additional Information**
When the cluster creation completes the DB will be updated by the agent.

**Comment by mckaymic** [comment]
- cluster_id should be generated by the API not passed in
- cluster_name should be saved as a field called "registered_name"
- https://github.com/razee-io/Razeedash-api/blob/master/app/routes/install/index.js#L29 will need to be updated to create a config-map with the cluster name and other meta data

**Comment by mckaymic** [comment]
Also, for pre-"registered" clusters the install API should be a 1-time use.  Once the install URL is used with a cluster-id passed to it, then subsequent requests will return a 410

https://github.com/razee-io/Razeedash-api/blob/master/app/routes/install/index.js#L29

**Comment by yingwang-us** [comment]
add state: {"preregister", "pending", "registered" }
total cluster limit: { 20,000, configurable through feature-flag }

**Comment by finken2** [comment]
@mckaymic 
1) Will the register API take labels/tags as input?
2) Were we in agreement that the register API should return the URL for attaching the cluster, in addition to the cluster ID?

**Comment by mckaymic** [comment]
@finken2 haha.  I don't see 90% of emails from Github so sorry I missed this one.
1. Maybe/Eventually?.  That will come as a separate feature after cluster register but it might be a separate call to add the labels
2. Yes, the register API should return the URL to attach a cluster with (amongst other metadata)
