### ISSUE TITLE
Razee setting deleted=false on some resources even though they are not deleted on the cluster

### ISSUE THREAD

**Issue by cherylfbrown** [razee-io/Razee#111]
**Describe the bug**
We have the `razee/watch-resource=lite` label on a Subscription resource in an OpenShift cluster running in Azure, and we see Razee picks it up and it’s returned in the resources collection with deleted=false. After some period of time, Razee starts returning the resource with deleted=true, even though it is clearly still there on the cluster and there are no issues with it. After some time again, approximately and hour, the deleted flag gets set back to false. It seems to be randomly cycling the flag between false and true even though no changes have been made on the cluster.

Please see for more details: https://cognitive-app.slack.com/archives/CHV0VFJ69/p1592503088273700

We can also provide login cluster info if needed.

**Comment by alewitt2** [comment]
problem found. In watch-keeper <= 0.5.2 there is a bug where an extra `}` made its way into the query params. This caused a 400 BadRequest, but didnt fail the Polling sequence, and therefore we still sent a `/sync` to  razeedash. On receiving the sync msg, and not seeing a resource for over an hour, razeedash marks an item deleted=true.

The extra `}` was removed in watch-keeper 0.5.3 and this should no longer be an issue. I also created PR https://github.com/razee-io/Watch-keeper/pull/148 to be more selective in which error codes we allow to continue and which ones should fail the sync.
