### ISSUE TITLE
Ensure all deployments have proper Kube checks and limits in place

### ISSUE THREAD

**Issue by mckaymic** [razee-io/Razee#118]
- liveness check
- readiness check
- resource request
- resource limit

This is needed for SatCon beta.

**Comment by alewitt2** [comment]
is it necessary to have readiness? i dont think any of our deployments take requests from kube, so i dont think we would need that.

- WatchKeeper
  - [ ] liveness check
  - [ ] readiness check - `NA`?
  - [ ] resource request
  - [ ] resource limit

- RemoteResource
  - [ ] liveness check
  - [ ] readiness check - `NA`?
  - [ ] resource request
  - [ ] resource limit

- MustacheTemplate
  - [ ] liveness check
  - [ ] readiness check - `NA`?
  - [ ] resource request
  - [ ] resource limit

- ClusterSubscription
  - [ ] liveness check
  - [ ] readiness check - `NA`?
  - [ ] resource request
  - [ ] resource limit

**Comment by mckaymic** [comment]
We are good with no readniness checks since we don't have any inbound traffic

**Comment by nathanleviere** [comment]
merged
