### ISSUE TITLE
Resources endpoint - ability to filter out deleted records

### ISSUE THREAD

**Issue by cherylfbrown** [razee-io/Razee#124]
**Is your feature request related to a problem? Please describe.**
We have scenarios where certain resources are getting created and deleted frequently on our clusters, and we do not care about getting the resources that are deleted from the resources endpoint in RazeeDash API.

**Describe the solution you'd like**
We would like to be able to do GET queries with a **deleted=false** param: `https://marketplace.redhat.com/api/collector/v2/resources?kind=Subscription&cluster_id=<cluster ID>&name=<operator name>&deleted=false`

**Describe alternatives you've considered**
If there is a way to periodically remove resource records where deleted=true from the resources collection that could also solve this issue. We could potentially implement our own process to do that.

**Comment by ethanstjohn** [comment]
Issue is no longer needed. Asked enhancement already built into code.
