### ISSUE TITLE
Resources endpoint - ability to query on namespace

### ISSUE THREAD

**Issue by cherylfbrown** [razee-io/Razee#125]
**Is your feature request related to a problem? Please describe.**
We use the RazeeDash API resources endpoint to check when a Subscription resource in a given namespace has been applied to the cluster. We do this by calling `GET https://marketplace.redhat.com/api/collector/v2/resources?kind=Subscription&cluster_id=<cluster ID>&name=<operator name>&limit=10000`. Then we have to loop through each result returned to check if `searchableData.namespace` matches the namespace we are looking for.

**Describe the solution you'd like**
It would be more efficient if the `GET /resources` endpoint had a `namespace` query param available so we could call:  `GET https://marketplace.redhat.com/api/collector/v2/resources?kind=Subscription&cluster_id=<cluster ID>&name=<operator name>&namespace=<namespace>`

**Comment by ethanstjohn** [comment]
Issue is no longer needed. Asked enhancement already built into code.
