### ISSUE TITLE
Resources query: totalCount should show total count

### ISSUE THREAD

**Issue by finken2** [razee-io/Razee#127]
resources query with `limit` should only return that `limit` of items, but the `totalCount` should return the total count of items that fit the filter. If no filter was supplied, it should be the over all total. 

This was working at one point, but regressed. 

Example:
```query ($org_id: String!) {
  resources(orgId: $org_id, sort: [{field:"searchableData.kind",desc:true}], limit: 500) {
    count
    totalCount
    resources {
      id
      orgId
      clusterId
      lastModified
      selfLink
      updated
      subscription {uuid name}
      searchableData
      cluster { name }
    }
  }
}
```

returns:
```
{
  "data": {
    "resources": {
      "count": 500,
      "totalCount": 500,
      "resources": [
        {...
```

I have over 9,000 items, and the total count should represent that.

**Comment by finken2** [comment]
@michael-topchiev Thanks for working on this, `totalCount` does seem to be working now. However... at one point, i think the `count` used to indicate how many items matched the filter, even if it was more than was returned. 

For example:
1) i request all resources w/ no filter, limit: 100.  count and totalCount would match, both 9,000
2) i request all resources w/ a filter that would give me 300 items, `limit: 100`.  count would be 300, totalCount would be 9,000, and 100 items returned.

Let me know if that makes sense, or if we could add a filteredCount.  Right now, all the count does is tell me how many things are coming back, which isn't that interesting since i could just .length 'em.

**Comment by carrolp** [comment]
@finken2 I'll have to dig into the code to be sure, but I don't think totalCount ever did or could have returned the total number _without the filter applied_.  I.e. `totalCount` should be the total number of matching records, `total` should be the total number returned in this payload.  Which yes, you could get by `.length`.  To have a query for filtered data _also_ return info about unfiltered data I think would require having the backend do twice as many queries.  As you noted originally, "the totalCount should return the total count of items that fit the filter" :-).

**Comment by carrolp** [comment]
That said, there may be some bugs in the handling (filtering items out _after_ the limit is applied), that we've been finding in the current work around paging.

**Comment by carrolp** [comment]
@finken2 paging fixes to behave as I note above are already delivered, can  you verify and close?

**Comment by finken2** [comment]
Discussed with paul and settled on using resourcesCount query for the data i need.  Just to put a bow on this one, my original comment here had a typo. My most recent comment was what i wanted, but we agreed it didn't make a ton of sense for `totalCount` to reflect things w/o the filter applied (even though it did at one point long ago).
