### ISSUE TITLE
Docs: typo

### ISSUE THREAD

**Issue by orgcontrib** [razee-io/Razee#137]
Having a huge README.md repo file instead of proper docs/pages/wiki, while it may look neat and easy, is not exactly optimal (especially for small squads/teams). At least this is my humble opinion.

+ typo 😭 
Make sure the end of the mongo URL has `/razeedash?ssh=true`.
+ no typo 😄 
Make sure the end of the mongo URL has `/razeedash?ssl=true`.

**Comment by dalehille** [comment]
Thanks for the fix @orgcontrib!  

I agree with your comments on the readme and hope it's something we can get updated soon
