### ISSUE TITLE
Followed the Readme but was not able to get the remoteresource created. Update in documentation is required

### ISSUE THREAD

**Issue by bgshri** [razee-io/Razee#152]
Followed the Readme but was not able to get the remote resource created. An update in documentation is required.

**Comment by carrolp** [comment]
@bgshri Can you elaborate on where you got stuck, what error messages you received, etc?

**Comment by carrolp** [comment]
@bgshri Any updates on this?

**Comment by carrolp** [comment]
Closing as stale.  If you have a chance to provide more details, please reopen.
