### ISSUE TITLE
razee with aws

### ISSUE THREAD

**Issue by soufianez75** [razee-io/Razee#21]
Hello,

I have an issue when I want push razee in my aws eks cluster
caused "exec: \"sh/liveness.sh\": permission denied": unknown
0s          Normal    Killing                      pod/mustachetemplate-controller-66478dd9dd-82fz4    Killing container with id docker://mustachetemplate-controller:Container failed liveness probe.. Container will be killed and recreated.
0s          Normal    Pulling                      pod/mustachetemplate-controller-66478dd9dd-82fz4    pulling image "quay.io/razee/mustachetemplate:0.0.3"
0s          Normal    Pulled                       pod/mustachetemplate-controller-66478dd9dd-82fz4    Successfully pulled image "quay.io/razee/mustachetemplate:0.0.3"
0s          Normal    Created                      pod/mustachetemplate-controller-66478dd9dd-82fz4    Created container
0s          Normal    Started                      pod/mustachetemplate-controller-66478dd9dd-82fz4    Started container
0s          Warning   FailedCreatePodSandBox       pod/mongo-6cb8568cb7-7wjdg                          (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "1f81dc0230d527c43c0f85cc907fff9511c1a70498168260ccfca062dc420230" network for pod "mongo-6cb8568cb7-7wjdg": NetworkPlugin cni failed to set up pod "mongo-6cb8568cb7-7wjdg_razee" network: add cmd: failed to assign an IP address to container
0s          Warning   BackOff                      pod/razeedash-api-57bdf94d59-zfss7                  Back-off restarting failed container
0s          Normal    Pulling                      pod/razeedash-5d5c4dcf49-krzw5                      pulling image "quay.io/razee/razeedash:0.1.0"
0s          Normal    EnsuringLoadBalancer         service/razeedash-lb                                Ensuring load balancer
0s          Warning   CreatingLoadBalancerFailed   service/razeedash-lb                                Error creating load balancer (will retry): failed to ensure load balancer for service razee/razeedash-lb: unsupported load balancer affinity: ClientIP
0s          Warning   Unhealthy                    pod/mustachetemplate-controller-66478dd9dd-82fz4    Liveness probe failed: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"sh/liveness.sh\": permission denied": unknown
0s          Normal    SandboxChanged               pod/mongo-6cb8568cb7-7wjdg                          Pod sandbox changed, it will be killed and re-created.
1s          Normal    Pulled                       pod/razeedash-5d5c4dcf49-krzw5                      Successfully pulled image "quay.io/razee/razeedash:0.1.0"
0s          Warning   BackOff                      pod/razeedash-api-57bdf94d59-zfss7                  Back-off restarting failed container
0s          Normal    EnsuringLoadBalancer         service/razeedash-lb                                Ensuring load balancer
0s          Warning   CreatingLoadBalancerFailed   service/razeedash-lb                                Error creating load balancer (will retry): failed to ensure load balancer for service razee/razeedash-lb: unsupported load balancer affinity: ClientIP

You have test the install on eks ?

Regards

**Comment by alewitt2** [comment]
we havent explicitely tested with aws. is it normal for them to block liveness scripts from running within a container?

**Comment by soufianez75** [comment]
I have migrate the ALB type 
but I have an issue with razeedash

AME                                               READY   STATUS                       RESTARTS   AGE
pod/featureflagsetld-controller-b57544d7b-rqlrl    1/1     Running                      0          38h
pod/kapitan-delta-7995d6b896-l5dt6                 1/1     Running                      0          41h
pod/managedset-controller-7c5f8467f6-54ggs         1/1     Running                      0          39h
pod/mongo-6cb8568cb7-x7gs7                         1/1     Running                      0          38h
pod/mustachetemplate-controller-66478dd9dd-82fz4   1/1     Running                      494        41h
pod/razeedash-5d5c4dcf49-krzw5                     0/1     CreateContainerConfigError   0          41h
pod/razeedash-api-7575c5ddf4-jswjc                 1/1     Running                      0          14h
pod/remoteresource-controller-6c896dcd95-m6ng9     1/1     Running                      0          39h
pod/remoteresources3-controller-6cbdc44c7-lw8js    1/1     Running                      0          39h
pod/watch-keeper-6f665b4bb8-h4jzr                  1/1     Running                      0          5m9s

how change this values

Environment:
      MONGO_URL:          <set to the key 'mongo_url' in secret 'razeedash-secret'>         Optional: false
      OAUTH_SECRET_KEY:   <set to the key 'oauth_secret_key' in secret 'razeedash-secret'>  Optional: true
      GITHUB_URL:         https://github.com/
      GITHUB_API:         https://api.github.com/
      ROOT_URL:           <set to the key 'root_url' of config map 'razeedash-config'>           Optional: false
      RAZEEDASH_API_URL:  <set to the key 'razeedash_api_url' of config map 'razeedash-config'>  Optional: true
      app_name:           Razeedash

?

Regards

**Comment by kitch** [comment]
@soufianez75 I think you might be missing step 5 from this howto.

https://github.com/razee-io/Razee

```
RAZEEDASH_LB=$(kubectl get service razeedash-lb -n razee -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
RAZEEDASH_API_LB=$(kubectl get service razeedash-api-lb -n razee -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
kubectl create configmap razeedash-config -n razee \
  --from-literal=root_url=http://"${RAZEEDASH_LB}":8080/ \
  --from-literal=razeedash_api_url=http://"${RAZEEDASH_API_LB}":8081/
```

**Comment by alewitt2** [comment]
I updated the mustachetemplate and the fix is out for the liveness issue. 

you should be able to change all of those values yourself.
```
kubectl edit configmap -n razee razeedash-config
kubectl edit secret -n razee razeedash-secret
```
you cant change the values for `GITHUB_URL` `GITHUB_API` `app_name` unless you manually apply the razeedash yaml (ie. download resource, edit it locally, apply file)

**Comment by alewitt2** [comment]
@kitch its possible his aws cluster doesnt support a loadbalancer (i dont think free iks clusters do).

**Comment by kitch** [comment]
@alewitt2 yes, this is also a possibility. or it may be that when running the patch commands on the configmap that an external ip was not yet assigned. Different LB providers take different amounts of time for the external-ip to be assigned. So may just need to rerun.

**Comment by geoffcorey** [comment]
@soufianez75 I just merged an updated to step 5 on the README.md that may resolve your issue.   See if that helps and let me know.

**Comment by soufianez75** [comment]
OK I will test in few days
thanks
