### ISSUE TITLE
Need better clarity around how to use Razee with IBM Cloud Database for MongoDB

### ISSUE THREAD

**Issue by jpapejr** [razee-io/Razee#23]
I gave this a shot by provisioning a new IBM Cloud Databases for MongoDB instance and then tried to use the mongodb connection string provided: 

`mongodb://$USERNAME:$PASSWORD@c28c997f-c6eb-4e1d-a7df-325367ad9f11-0.0135ec03d5bf43b196433793c98e8bd5.databases.appdomain.cloud:31888,c28c997f-c6eb-4e1d-a7df-325367ad9f11-1.0135ec03d5bf43b196433793c98e8bd5.databases.appdomain.cloud:31888/ibmclouddb?authSource=admin&replicaSet=replset`

But all I could get were connection errors from the mongodb connection lib: 

```
razeedash-645c4d866b-l9bpz razeedash MongoNetworkError: connection 2 to c28c997f-c6eb-4e1d-a7df-325367ad9f11-0.0135ec03d5bf43b196433793c98e8bd5.databases.appdomain.cloud:31888 closed
razeedash-645c4d866b-l9bpz razeedash     at Socket.<anonymous> (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:276:9)
razeedash-645c4d866b-l9bpz razeedash     at Object.onceWrapper (events.js:315:30)
razeedash-645c4d866b-l9bpz razeedash     at emitOne (events.js:116:13)
razeedash-645c4d866b-l9bpz razeedash     at Socket.emit (events.js:211:7)
razeedash-645c4d866b-l9bpz razeedash     at TCP._handle.close [as _onclose] (net.js:561:12)
```

**Comment by geoffcorey** [comment]
Creating connection strings is documented with razeedash-api repo.  I can update the main site with this information as well. 

With IBM Cloud Databases for MongoDB you need to add `&ssl=true` on the end of the connect string and then base64 the string for the secret.   Example:

```bash
echo -n "mongodb://$USERNAME:$PASSWORD@c28c997f-c6eb-4e1d-a7df-325367ad9f11-0.0135ec03d5bf43b196433793c98e8bd5.databases.appdomain.cloud:31888,c28c997f-c6eb-4e1d-a7df-325367ad9f11-1.0135ec03d5bf43b196433793c98e8bd5.databases.appdomain.cloud:31888/ibmclouddb?authSource=admin&replicaSet=replset&ssl=true" | base64
```

**Comment by geoffcorey** [comment]
@jpapejr did that resolve the issue?

**Comment by jpapejr** [comment]
Sure was. Thx.
