### ISSUE TITLE
Improve documentation regarding labeling resources

### ISSUE THREAD

**Issue by mckaymic** [razee-io/Razee#24]
The section describing how to label resource only talks about individual resources, not how to label entire namespaces `https://github.com/razee-io/Razee#step-2-visualize-deployment-information-in-razeedash`.  In addtion, the `kubectl label` command should be used instead of editing the YML file directly ( `label namespace default 'razee/watch-resource=true'` )

**Comment by alewitt2** [comment]
agree we should use `kubectl label`

also the better docs on labeling exist in the watch-keeper readme. i think we just need to add a link to [those docs](https://github.com/razee-io/Watch-keeper/#collecting-resources) here.

**Comment by alewitt2** [comment]
ad54680696daaf37f7b76ba1202478086dc1ad7b
