### ISSUE TITLE
Url values in the Razeedash-config ConfigMap require trailing `/`

### ISSUE THREAD

**Issue by jpapejr** [razee-io/Razee#31]
Granted the example docs *do* show a trailing `/` character after the `root_url` and `razeedash_api_url` it's not exactly clear that those really are required. Failure to include these final `/`'s will result in values like this in the `Install Razee Agent` field in the org management panel (note the missing slash between my domain and the start of the path): 

```
kubectl create -f "https://razeedash-api.kubedclouds.usapi/install/cluster?orgKey=xxxxxxxxx"
```

If we were so inclined we could easily look for a trailing slash in the ConfigMap value and add one if it was omitted. (Or we could firm up the docs indicating that the trailing slash should be there).

**Comment by dalehille** [comment]
@jpapejr I updated the docs to mention the trailing slashes.  Also I opened https://github.com/razee-io/Razeedash/pull/103 so the `Install Razee Agent` command will include the trailing slash if it wasn't found

**Comment by jpapejr** [comment]
Looks good. Thanks!
