### ISSUE TITLE
Question: How long does it take for inactive clusters to "fall off" of the dashboard completely?

### ISSUE THREAD

**Issue by jpapejr** [razee-io/Razee#33]
I have a few clusters that have been rightly marked inactive now (after ~24 hours of not reporting in, it seems). When would I expect to see these clusters not reported on the `Clusters` view any longer and those associated Resources removed from the `Resources` view?

**Comment by alewitt2** [comment]
@dalehille @rmgraham please respond

**Comment by jpapejr** [comment]
Data point: 

<img width="765" alt="Screen Shot 2019-06-20 at 9 36 49 AM" src="https://user-images.githubusercontent.com/213203/59876700-48e47f80-9372-11e9-86b1-391d69701300.png">

**Comment by dalehille** [comment]
We don't have any cluster or resource auto cleanup enabled for inactive clusters -- so for now the resources will continue to show up on the UI.   I opened https://github.com/razee-io/Razeedash/issues/97 in RazeeDash so we can work on a solution.

**Comment by jpapejr** [comment]
Thx @dalehille - In the meantime, is it safe to purge the related records to these clusters and the resources watched from there from the mongo collections?

**Comment by dalehille** [comment]
yes, that shouldn't be a problem

**Comment by jpapejr** [comment]
Thx @dalehille - I'm working on getting familiar with the source for the dashboard (and getting things up locally to test) but in the meantime I came up with this quick solution https://github.com/jpapejr/razee-cluster-cleaner
