### ISSUE TITLE
Kapitan: Name already used by deepmind/kapitan

### ISSUE THREAD

**Issue by ademariag** [razee-io/Razee#35]
Hello Razee team,

just to let you know that Kapitan as a name is already used by this project https://github.com/deepmind/kapitan (Google, DeepMind) 
See also: 
* https://kapitan.dev
* https://medium.com/kapitan-blog

Do you think you could rename your Kapitan component to avoid confusion? As both projects are addressing the same problems, I think it would be extremely confusing for users of both projects.

Regards
Alessandro, on behalf of the Kapitan team

**Comment by mckaymic** [comment]
Hi @ademariag.  Thanks for reaching out to us.  Sorry I realized you posted this 19 days ago are we are just getting around to responding.

We generally refer to our tools as Razee and Kapitan is just a component of it.  We're looking right now on what it would take to rename.  It's easy to change the project name, but updating the Kube CRDs will take a bit more effort.

**Comment by ademariag** [comment]
@mckaymic hi, is there an update?

**Comment by alewitt2** [comment]
We plan to do the rename in the docs and our npm module to, but will keep the name in the CRDs.

**Comment by mckaymic** [comment]
@ademariag We've put it on our list of things to do next week.  Thanks `@stalebot` and for being patient @ademariag.

**Comment by uberspot** [comment]
Bump for stalebot

**Comment by alewitt2** [comment]
> Bump for stalebot

thanks, we are still planning on doing this.

**Comment by ademariag** [comment]
@alewitt2 thank you so much!

**Comment by alewitt2** [comment]
for all intents and purposes this is complete. Our code will support old name for a time being until users have time to move to new name. But going forward and via google search, we no longer show kapitan in our naming. Thanks.
