### ISSUE TITLE
Issue deploying

### ISSUE THREAD

**Issue by cooktheryan** [razee-io/Razee#36]
[rcook@goku multicloud]$ kubectl get pods -n razee
NAME                                           READY   STATUS    RESTARTS   AGE
featureflagsetld-controller-6686c998dc-86z4h   1/1     Running   0          3m44s
kapitan-delta-5d4cc865f5-k2p57                 1/1     Running   0          4m9s
managedset-controller-67f9899f46-vbzjv         1/1     Running   0          3m43s
mustachetemplate-controller-55684955b4-7d4kc   1/1     Running   0          3m42s
remoteresource-controller-6d79b48bb9-tspwf     1/1     Running   0          3m42s
remoteresources3-controller-79cdb96b4c-kw5fw   1/1     Running   0          3m41s
[rcook@goku multicloud]$ kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/resource.yaml
error: error validating "https://github.com/razee-io/Razee/releases/latest/download/resource.yaml": error validating data: [ValidationError(RemoteResource.spec.requests[0]): unknown field "options" in io.razee.kapitan.v1alpha1.RemoteResource.spec.requests, ValidationError(RemoteResource.spec.requests[1]): unknown field "options" in io.razee.kapitan.v1alpha1.RemoteResource.spec.requests]; if you choose to ignore these errors, turn validation off with --validate=false
[rcook@goku multicloud]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+3569a06", GitCommit:"3569a06", GitTreeState:"clean", BuildDate:"2019-06-12T15:47:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+d4417a7", GitCommit:"d4417a7", GitTreeState:"clean", BuildDate:"2019-06-12T15:47:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Current version of the repository:
commit 0f88fb5be03d2b0fda88e9eec999da357ca26f5d (HEAD -> master, origin/master, origin/HEAD)

**Comment by alewitt2** [comment]
im not able to replicate this issue on kube version 1.13.7. What does your remote resource crd look like `kubectl get crd remoteresources.kapitan.razee.io -o yaml`? and what does the file thats failing validation look like (whatever you downloaded from `https://github.com/razee-io/Razee/releases/latest/download/resource.yaml`)?

**Comment by cooktheryan** [comment]
@alewitt2 
```
kubectl get crd remoteresources.kapitan.razee.io -o yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    razee.io/commit-sha: 63b370904076dbab2722bf64e0bd41e466ca55a4
    razee.io/git-repo: https://github.com/razee-io/RemoteResource.git
  creationTimestamp: "2019-08-09T16:40:37Z"
  generation: 1
  name: remoteresources.kapitan.razee.io
  resourceVersion: "19210924"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/remoteresources.kapitan.razee.io
  uid: 6a9dfd79-bac4-11e9-bee9-12da23a19d36
spec:
  conversion:
    strategy: None
  group: kapitan.razee.io
  names:
    kind: RemoteResource
    listKind: RemoteResourceList
    plural: remoteresources
    shortNames:
    - rr
    singular: remoteresource
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            requests:
              items:
                oneOf:
                - properties:
                    options:
                      properties:
                        url:
                          format: uri
                          type: string
                      required:
                      - url
                      type: object
                  required:
                  - options
                  type: object
                - properties:
                    options:
                      properties:
                        uri:
                          format: uri
                          type: string
                      required:
                      - uri
                      type: object
                  required:
                  - options
                  type: object
                - properties:
                    url:
                      format: uri
                      type: string
                  required:
                  - url
                  type: object
                - properties:
                    uri:
                      format: uri
                      type: string
                  required:
                  - uri
                  type: object
                properties:
                  optional:
                    type: boolean
                type: object
              type: array
          required:
          - requests
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: RemoteResource
    listKind: RemoteResourceList
    plural: remoteresources
    shortNames:
    - rr
    singular: remoteresource
  conditions:
  - lastTransitionTime: "2019-08-09T16:40:37Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
```

kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/resource.yaml is what I am running at the time so not using a release

**Comment by cooktheryan** [comment]
I got around it by not deploying the *remoteresource* due to an error of me trying to fix it and then removing my not working fix

```
[rcook@goku ~]$ vi resource.yaml 
[rcook@goku ~]$ oc create -f resource.yaml 
persistentvolume/mongo-pv-volume created
persistentvolumeclaim/mongo-pv-claim created
deployment.apps/mongo created
service/mongo created
secret/razeedash-secret created
error: unable to recognize no matches for kind "RemoteResources" in version "kapitan.razee.io/v1alpha1"
[rcook@goku ~]$ vi resource.yaml 
[rcook@goku ~]$ oc create -f resource.yaml 
remoteresource.kapitan.razee.io/razeedash created
service/razeedash-lb created
service/razeedash-api-lb created
Error from server (AlreadyExists): persistentvolumes "mongo-pv-volume" already exists
Error from server (AlreadyExists): persistentvolumeclaims "mongo-pv-claim" already exists
Error from server (AlreadyExists): deployments.apps "mongo" already exists
Error from server (AlreadyExists): services "mongo" already exists
Error from server (AlreadyExists): secrets "razeedash-secret" already exists
```

**Comment by alewitt2** [comment]
hmm. theres been several changes to remoteresource over the last month and it looks like you are on the latest version now. It appears you are in a working state. let me know if there is something you think i should look into further. 

fyi: `error: unable to recognize no matches for kind "RemoteResources" in version "kapitan.razee.io/v1alpha1"` sometimes can show up if you try to create a remoteresource before kube has fully registered the RemoteResource CRD.

**Comment by cooktheryan** [comment]
ya it definitely appeared like a timing thing.
