### ISSUE TITLE
Create new Identity CRD

### ISSUE THREAD

**Issue by alewitt2** [razee-io/Razee#59]
Create a new identity crd that will be able to assemble info about the cluster as well as custom info specified by the user to create a `data` section in the identity resource to be used by FeatureFlagSetLD and watch-keeper.

This will provide a consistent identity piece across all components.

**Comment by alewitt2** [comment]
Might consider breaking the baseTemplateController code that looks up env/envFrom data into its own module within razeedeploy-core, and importing that into IdentityController.

**Comment by nathanleviere** [comment]
Will not implement this.
