### ISSUE TITLE
New and Upcoming Bugs

### ISSUE THREAD

**Issue by alewitt2** [razee-io/Razee#60]
- [x] Update schemas: In kube 1.16 schemas are becoming mandatory and more strict. our current schemas aren't valid/structural, so we need to update all crd schemas to be ready for 1.16. See [docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema)
- [ ] Stop using selfLink: selfLink is being deprecated around 1.20/1.21. we will need to either transition to creating the selfLink for the uses that we need it, or switching to a different attribute. I know selfLink is used in watch-keeper and composite-controller, need to see if it used anywhere else (maybe kube-class). see [issue](https://github.com/kubernetes/enhancements/issues/1164)
- [x] Enforcement: In 1.16, it appears kube has stopped sending ADDED every minute or so to watches. Need to investigate if this is true, and if so, how do we continue doing enforcement for our code.

**Comment by alewitt2** [comment]
Enforcement: its actually the watch being closed and restarted that created the behavior that we have been seeing. It looks like in 1.16 they fixed CRDs to have the normal timeout of 30 min instead of 1.5 min. We can mimick this behavior by setting the query selector timeoutSeconds to our desired interval (and allow a env to override the interval to shorten for demo purposes). We should also revisit this to optimize to use the longer watches, but this means we need to better handle enforcement of children, checking remote resources, and re-templating mtps. Probably will invlove more watches of the resources we care about (ie children or configmaps) as well as creating fake poll events to pump into the evant handler to cause the cycle to start as desired (we had this code at one point, just need to go through the comit history to find it.)

**Comment by alewitt2** [comment]
Schemas:
1. hard cutover at 1.16, this means:
    - we update our crd apiVersion to apiextensions.k8s.io/v1
    - we update our resource apiVersions to v1alpha2
    - we update our schemas to be structural
    - we update code to match new schemas
    - existing resources cannot be applied until they match the updated schema and apiVersions v1alpha2
2. name change, this means:
    - there is a coexistence period for Kubernetes <= 1.15. our controller/operator will support both <customResource>.deploy.razee.io v1alpha1 and <customResource>.operator.razee.io v1alpha2
    - <customResource>.deploy.razee.io v1alpha1 is what people use today
    - <customResource>.operator.razee.io v1alpha2 uses the new structural schema. once switched over, you'll be able to update your cluster without impact

**Comment by nathanleviere** [comment]
will also cover https://github.com/razee-io/FeatureFlagSetLD/issues/24 and https://github.com/razee-io/FeatureFlagSetLD/issues/23

**Comment by alewitt2** [comment]
moving selflink discussion to https://github.com/razee-io/Razee/issues/85
