### ISSUE TITLE
"Error applying file to kubernetes. StatusCode: 422 url: https://github.com/razee-io/Razeedash/releases/latest/download/resource.yaml message: Deployment.apps \"razeedash\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app\":\"razeedash\"}: `selector` does not match template `labels`

### ISSUE THREAD

**Issue by jharlow1** [razee-io/Razee#65]
**Describe the bug**
On initial install, razeedash Deployment is failing. Logs from the remoteresource controller show:

```
"Error applying file to kubernetes. StatusCode: 422 url: https://github.com/razee-io/Razeedash/releases/latest/download/resource.yaml message: Deployment.apps \"razeedash\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app\":\"razeedash\"}: `selector` does not match template `labels`
```

**To Reproduce**

1. Fresh IBM Kubernetes Service cluster (Kube 1.14.8_1536)
2. kubectl apply -f https://github.com/razee-io/Kapitan-delta/releases/latest/download/resource.yaml
3. kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/resource.yaml

**Expected behavior**
razeedash to be deployed

**Kubernetes Version (kubectl version):**
 - Client: n/a 
 - Server:  1.14.8

**Comment by adamkingit** [comment]
Try version 1.6.3. If that update doesn't apply, then you will have to edit the deployment to unblock the updates. (Sorry). 
<namespace> == whatever namespace you deployed razeedash to.
kubectl -n <namespace> edit deployment razeedash 

Set the matchLabels like https://github.com/razee-io/Razeedash/blob/master/kubernetes/razeedash/resource.yaml#L25-L26

and set template.metadata.labels to just be `app: razeedash`, deleting any other labels.
