### ISSUE TITLE
Sign in GHE jumps to wrong URL and there is no way to re-configure

### ISSUE THREAD

**Issue by dove-young** [razee-io/Razee#67]
**Describe the bug**

**To Reproduce**
1. Setup GHE
2. Input API Url as `https://api.github.ibm.com` and Github URL as `https://github.ibm.com`
3. Save configuration
4. Click `Sign in` button, it jumps to URL `https://https//github.ibm.com/login/oauth/`
**Expected behavior**

And there is no approach to re-configure and correct configurations.

**Comment by dalehille** [comment]
@dove-young you can reset this by getting a mongo shell opened for your database and either

1)  edit the record in the`db.meteor_accounts_loginServiceConfiguration` collection and update `gheURL` and `gheAPI`

or

2) run `db.meteor_accounts_loginServiceConfiguration.remove({})` to completely remove the entry and get all the oauth propmts again

**Comment by dalehille** [comment]
@dove-young did this fix your problem?
