### ISSUE TITLE
Need the ability to create a new org via an API

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#69]
**Is your feature request related to a problem? Please describe.**
Need the ability to create a new org with a given ID via an API.

We will be supporting deployment of operators via Razee to client clusters and our solution will be supporting many clients. In order to isolate one clients clusters from another, we would like to be able to create one org within Razee per client. We would like to be able to specify the new org's ID.

**Describe the solution you'd like**
An API where we can pass in an org ID that we specify and any other info Razee requires, and it will create a new org with the given ID.

**Describe alternatives you've considered**
We can store a map of client account IDs to cluster IDs for a given client, and still accomplish our use cases, but it would make for a better integration if Razee could help keep track of this by using an org.

**Additional context**
Flows are documented here: https://ibm.box.com/s/2zkm8an33wi693feq0uv3eajl2k8r7c1 and have been discussed with Mike McKay.

**Comment by dalehille** [comment]
this is available with the 0.4.0 release https://github.com/razee-io/Razeedash-api/releases/tag/0.4.0
