### ISSUE TITLE
Need a RESTful API to expose data from the Razeedash database

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#70]
**Is your feature request related to a problem? Please describe.**
Need a RESTful API to expose cluster, node, deployment, pod, and other resource info from the Razeedash database in a secure manner.

We will have a single instance of Razeedash set up which will have clusters from multiple clients registered (e.g. each clients cluster will have Watchkeeper installed and reporting back to the single Razeedash instance). We would like to display list of clusters, detailed cluster and node information, deployment, pod, and other resource information back to our clients in a Dashboard view.

**Describe the solution you'd like**
A RESTful API to expose, query, sort, and filter data from the Razeedash database including cluster, node, deployment, pod, and other resource info. For example, ability to query on deployment status and specifically what is failing is one of our use cases. We would also like the ability to query across one org's clusters for a deployment. If you need an exhaustive list of use cases, please let me know.

Data should not be exposed externally without auth in place.

**Describe alternatives you've considered**
We can query the Razeedash database directly or set up our own API shim, but we would prefer the Razee team to do that to isolate us from any changes you may make to the underlying database schema.

**Additional context**
Flows are documented here: https://ibm.box.com/s/2zkm8an33wi693feq0uv3eajl2k8r7c1 and have been discussed with Mike McKay.

If you would like separate Issues split out for this work, please let me know.

**Comment by dalehille** [comment]
this is available with the 0.4.0 release https://github.com/razee-io/Razeedash-api/releases/tag/0.4.0
