### ISSUE TITLE
Need a notification from Razee whenever a cluster phones home to Razeedash for the first time

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#71]
**Is your feature request related to a problem? Please describe.**
Need a notification from Razee whenever a cluster phones home to Razeedash for the first time, after the Watchkeeper agent has been installed.

**Describe the solution you'd like**
Webhook, event, or some type of notification to a REST API the first time a cluster connects back to Razeedash. The event should include the org ID, cluster ID, and cluster name associated with the cluster (if one was specified in a configmap).

**Describe alternatives you've considered**
We can poll Razee for clusters and check when the cluster in question is first listed there (assuming an API is implemented for this, or we could query the db directly). However, the ability to be notified would make for a better integration with Razee.

**Additional context**
Flows are documented here: https://ibm.box.com/s/2zkm8an33wi693feq0uv3eajl2k8r7c1 and have been discussed with Mike McKay.

**Comment by rmgraham** [comment]
Added in https://github.com/razee-io/Razeedash-api/pull/104/files

**Comment by rmgraham** [comment]
Works in release 0.4.1. To enable, set a url to `add_cluster_webhook_url` in `razeedash-secret` in the razee namespace.
