### ISSUE TITLE
Assistance or documentation with setting up a production ready instance of Razeedash API

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#72]
**Is your feature request related to a problem? Please describe.**
We need guidance or best practices on setting up a product ready instance of the Razeedash db and APIs. 

**Describe alternatives you've considered**
Razee team hosts the instance for us.

**Additional context**
Flows are documented here: https://ibm.box.com/s/2zkm8an33wi693feq0uv3eajl2k8r7c1 and have been discussed with Mike McKay.

**Comment by nathanleviere** [comment]
@mckaymic - will meet with you soon to talk about this.
