### ISSUE TITLE
Need best practices documentation for formatting remote resources

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#73]
**Is your feature request related to a problem? Please describe.**
Need a set of documentation on how to format remote resources in a way that Razee understands.

We have noticed instances where yamls that work with kubectl apply do not work with Razee so need to understand exactly what Razee expects, and if there are any suggested best practices on how to set them up (e.g. using List object instead of `---`).

**Describe alternatives you've considered**
Trial and error

**Additional context**
Flows are documented here: https://ibm.box.com/s/2zkm8an33wi693feq0uv3eajl2k8r7c1 and have been discussed with Mike McKay.

**Comment by nathanleviere** [comment]
@mckaymic will meet with you soon to discuss the basics of this request.
