### ISSUE TITLE
Mechanism for removing Razee agent components from a cluster

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#76]
**Is your feature request related to a problem? Please describe.**
We are going to have customers installing the Razee agent on their clusters, and envision scenarios where they may no longer want the Razee agent components installed on their clusters anymore. Need a mechanism to cleanly remove everything installed by the "Install Razee Agent" command (e.g. kubectl create -f "http://169.45.231.109:8081/api/install/cluster?orgKey=orgApiKey-75dd7435-4567-4d5f-a1c9-a9735c55b1b4")

**Describe alternatives you've considered**
Tried `kubectl delete -f "http://169.45.231.109:8081/api/install/cluster?orgKey=orgApiKey-75dd7435-4567-4d5f-a1c9-a9735c55b1b4"` but it doesn't completely remove all installed components.

**Comment by alewitt2** [comment]
Initial thought: we will create a kubernetes Job to do uninstall steps. It is more complicated then just one command and will be easier if we can write a script to do the proper steps that can wait for confirmation before proceeding.

**Comment by mckaymic** [comment]
Included with https://github.com/razee-io/razeedeploy-delta/pull/51

**Comment by alewitt2** [comment]
the initial work is done for the install/remove jobs. will open another issue to get this integrated into razeedash/razeedash-api

https://github.com/razee-io/razeedeploy-delta/releases/download/0.3.1/job.yaml
where `{{ COMMAND }}` is either `install` or `remove`
and `{{ NAMESPACE }}` is the namespace to install everything into
and `{{ ARGS_ARRAY }}` is something like `["--rr", "--wk", "-a"]`

see here for all [install options](https://github.com/razee-io/razeedeploy-delta/blob/master/src/install.js#L35-L63) and here for all [remove options](https://github.com/razee-io/razeedeploy-delta/blob/master/src/remove.js#L33-L49) you can add to the ARGS_ARRAY
