### ISSUE TITLE
Need an API for deleting clusters

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#77]
**Is your feature request related to a problem? Please describe.**
Need the ability to remove a cluster from Razee programmatically in cases where customers no longer want their clusters to be registered with Razee.

**Describe the solution you'd like**
A RESTful API for deleting clusters in Razee.

**Comment by dalehille** [comment]
available in https://github.com/razee-io/Razeedash-api/releases/tag/0.6.0
