### ISSUE TITLE
Duplicate razee namespace creation in http://<razeedash-api-lb_external_IP>:8081/api/install/cluster?orgKey=orgApiKey-<org_api_key>

### ISSUE THREAD

**Issue by jiangchen2019** [razee-io/Razee#78]
**Describe the bug**
http://<razeedash-api-lb_external_IP>:8081/api/install/cluster?orgKey=orgApiKey-<org_api_key> includes the razee namespace creation twice. So there would always be an error. ```Error from server (AlreadyExists): namespaces "razee" already exists```

**To Reproduce**
1. GET http://<razeedash-api-lb_external_IP>:8081/api/install/cluster?orgKey=orgApiKey-<org_api_key> 
2. In result, line 1-5 and line 176 - 182. Deplicate razee namespace creation
3. Run `kubectl create -f http://<razeedash-api-lb_external_IP>:8081/api/install/cluster?orgKey=orgApiKey-<org_api_key>` and get an error like ```Error from server (AlreadyExists): namespaces "razee" already exists```

**Expected behavior**
No error message

**Screenshots**

**Kubernetes Version (kubectl version):**
 - Client: 1.14.9_1543
 - Server: 1.14.9_1543

**Additional context**

**Comment by mckaymic** [comment]
Will be fixed with https://github.com/razee-io/razeedeploy-delta/pull/51

**Comment by alewitt2** [comment]
the initial work is done for the install/remove jobs. will open another issue to get this integrated into razeedash/razeedash-api

https://github.com/razee-io/razeedeploy-delta/releases/download/0.3.2/job.yaml
where {{ COMMAND }} is either install or remove
and {{ NAMESPACE }} is the namespace to install everything into
and {{ ARGS_ARRAY }} is something like ["--rr", "--wk", "-a"]

see here for all install options and here for all remove options you can add to the ARGS_ARRAY
