### ISSUE TITLE
Support auth on add cluster callback APIs

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#80]
**Is your feature request related to a problem? Please describe.**
We implemented an add cluster callback API, but had to make it unauthenticated because Razee does not support a callback API that has authorization in place. We would like Razee to support auth on add cluster callback endpoints, because we are concerned about leaving our cluster callback endpoint open and exposed for attacks.

**Describe the solution you'd like**
Add an add cluster callback api key that can be specified in the razeedash-secret. Update Razee to pass this in as a header on each request to the add cluster callback API.

**Describe alternatives you've considered**
N/A

**Comment by ryangrahamnc** [comment]
We discussed this and determined a better option would be to allow a secret that has a list of key-value headers to send in the request (instead of hardcoding one Authorization header). So even though code has been merged, consider this issue still open.

**Comment by rmgraham** [comment]
Added in https://github.com/razee-io/Razeedash-api/pull/168/files
