### ISSUE TITLE
Support for only installing needed Razee agent components 

### ISSUE THREAD

**Issue by thecheryl** [razee-io/Razee#81]
**Is your feature request related to a problem? Please describe.**
For our use cases, when the Razee agent is installed on a cluster, we don't need the featureflagsetlid-controller, managedset-controller, or mustachetemplate-controller deployments. This is creating extra unneeded workload on clusters and making the setup time longer for each cluster where the agent is installed.

**Describe the solution you'd like**
A separate `/api/install/cluster` API or a way to configure the existing `/api/install/cluster` API such that it only deploys the required parts.

**Describe alternatives you've considered**
It looks like we could edit the razeedeploy-delta-resource-uris ConfigMap that comes back from the existing `/api/install/cluster` endpoint to remove the parts we don't need.

**Comment by alewitt2** [comment]
1. if you want to install components individually, you can also hit them directly (ie. remote-resource `https://github.com/razee-io/RemoteResource/releases/latest/download/resource.yaml`)
1. Yes your work around to remove uris from the uri configmap will work for your situation.
1. We are currently planning on creating a job to do the component install (tracking here https://github.com/razee-io/Razee/issues/74). Once created, we will allow for configuration on the job to only install the components you want.
