### ISSUE TITLE
Mechanism for getting all namespaces in a registered cluster

### ISSUE THREAD

**Issue by lnvuong** [razee-io/Razee#82]
**Is your feature request related to a problem? Please describe.**
We need to populate a list of namespaces for the cluster in our UI and need a mechanism to retrieve the list via Razee

**Describe alternatives you've considered**
Adding the watchkeeper label to all the namespaces

**Comment by alewitt2** [comment]
We now have a mechanism for polling the namespaces every hour completed in https://github.com/razee-io/Watch-keeper/pull/87. If you need more immediate data, you will need to wait for the next feature i am working on in https://github.com/razee-io/Watch-keeper/issues/88
