### ISSUE TITLE
Update website install links

### ISSUE THREAD

**Issue by IanMoroney** [razee-io/Razee#95]
**Describe the bug**
The links for installing Razee on the [website ](https://razee.io/#get-razee) still point to installing via:
`kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/resource.yaml`

It should point to:
`kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/razeedeploy.yaml`

**Comment by mckaymic** [comment]
@IanMoroney Thanks for the feedback.  I've updated the install links.  https://github.com/razee-io/Razee-io.github.io/commit/1395b348bc56d8605bd1f0313fca85301a837815.  FYI, we'll start working on a better way to get Razeedash install for folks soon.
