### ISSUE TITLE
Warnings while deploying razeedash-all-in-one.yaml

### ISSUE THREAD

**Issue by asm582** [razee-io/Razee#96]
**Describe the bug**
(node:18) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**To Reproduce**
On new cluster run 
1)  kubectl apply -f https://github.com/razee-io/Razee/releases/latest/download/razeedash-all-in-one.yaml
2) kubectl logs deploy/razeedash-api -n razee

**Expected behavior**
should run without deprecation warning

**Kubernetes Version (kubectl version):**
 - Client: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
 - Server:Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+IKS", GitCommit:"06b4447d3f958e995e61af88b750537b264d0fd7", GitTreeState:"clean", BuildDate:"2020-03-13T12:50:19Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mckaymic** [comment]
The fix is in master now.  It will get included in the next release.  Thanks @asm582 !
