### ISSUE TITLE
Razee Custom Resource Definitions Ownership

### ISSUE THREAD

**Issue by zach-source** [razee-io/Razee#98]
**Is your feature request related to a problem? Please describe.**
Yes. As apart of the Red Hat Marketplace Operator, we are installing razee CRDs into an [OLM](https://github.com/operator-framework/operator-lifecycle-manager) operated kubernetes (a.k.a. Openshift). These CRDs are unmanaged because Razee is not an Operator.

**Describe the solution you'd like**
We'd like to be able to namespace the Group at least to be applicable to our operator. This would be something like this: 

remoteresources3.deploy.razee.io -> remoteresources3.marketplace.redhat.com

**Describe alternatives you've considered**
Razee having an operator would help, but unfortunately we may still have this problem. We'd like to embed your controller to empower our operator with additional functionality. If your controller was golang, we could probably re-implement your controller code as well.

**Comment by alewitt2** [comment]
we do have plans to move to a golang implementation, just havent made it there yet.

what is it you are asking us to do?

**Comment by zach-source** [comment]
Spoke with @mckaymic on this one. I'll let him jump in, maybe grab ya.

**Comment by zach-source** [comment]
I was thinking about this @mckaymic - since you have your core logic split up into different libraries. We could probably just reimplement this file: https://github.com/razee-io/RemoteResourceS3/blob/master/src/index.js#L64

If we change these  [strings](https://github.com/razee-io/RemoteResourceS3/blob/master/src/index.js#L46) will we be able to put our own group/version?

We can just then add the CRD yaml to our operator and be off to the races.

When there is a golang API, we could do the same thing, just reimplement your controller.

**Comment by alewitt2** [comment]
@zach-source yes that would work. We are thinking that we dont have any better solutions at the moment and we will most likely parametrize this for you, so you can just set a couple build env variables, and when you pull in the latest code it should build into everything you need.

**Comment by zach-source** [comment]
Thanks @alewitt2 - that makes sense. Was wondering if that was necessary to do though Implementing and using your libs may be cleaner. It means we don't have to fork your build. Is the CRD generated at all? That is the only gap I see. We could make a golang project to just generate the CRDs and that would solve the issue.

**Comment by alewitt2** [comment]
well its going to be a fork no matter what, we are just talking about what the extent of the the fork is. Our thinking is to make it so you dont have to manually intervene at all, to make it as easy as possible, to keep your code up to date and avoid code drift.

the CRD is not generated, just checked in. the controller deployment.yaml is slightly generated.
